name: Build and Export APK

on:
  push:
    branches:
      - master

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '1.8'
          distribution: 'adopt'
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          android-sdk-version: '29'
      - name: Set up Android NDK
        uses: android-actions/setup-android-ndk@v2
        with:
          android-ndk-version: '23.1.7779620'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make autoconf automake git python binutils
          sudo apt-get install -y libtool-bin pkg-config flex bison gettext texinfo rsync
      - name: Get and compile external libraries
        run: |
          cd ./limbo-android-lib/src/main/jni
          # Add commands to download and compile external libraries here
      - name: Apply patches
        run: |
          cd ./limbo-android-lib/src/main/jni/qemu/
          patch -p1 < ../patches/qemu-5.1.0.patch
          cd ../../../glib/
          patch -p1 < ../patches/glib-2.56.1.patch
          cd ../../../SDL2/
          patch -p1 < ../patches/sdl2-2.0.8.patch
      - name: Build and export APK
        run: |
          cd ./limbo-android-lib/
          ./gradlew assembleRelease
          mkdir -p android/app/build/outputs/apk/release
          cp app/build/outputs/apk/release/app-release.apk android/app/build/outputs/apk/release/
      - name: Make limbo
        run: |
          export BUILD_GUEST=x86_64-softmmu
          make limbo
